printverbose("put raw file link")
printverbose("can be a link to a file stored on discord or on github etc")
local file = read()
printverbose("put download path")
local path = read()
local handle = io.open(path,"w")
local contents = http.get(file).readAll()
handle:write(contents)
handle:close()